#!/usr/bin/env python

Import("env")
Import("env_modules")

env_visual_shader = env_modules.Clone()

env_visual_shader.add_source_files(env.modules_sources, "*.cpp")
env_visual_shader.add_source_files(env.modules_sources, "vs_nodes/*.cpp")
if env["tools"]:
    env_visual_shader.add_source_files(env.modules_sources, "editor/*.cpp")
